### ISSUE TITLE
300% performance impact

### ISSUE THREAD

**Issue by Raynos** [CrabDude/trycatch#39]
I'm using the long stack traces implementation in trycatch.

My tests run in 5s without trycatch and in 15s with trycatch.

Having a performance penalty of 20-30% is normal, having one thats 300% slower seems crazy.

Is there anything that can be done to optimize this library ?

**Comment by CrabDude** [comment]
I tried for an hour to get this working, but there were dependency issues and I couldn't get it working for any version of node. Let me know if this is still an issue for you, or if you have a recommendation on getting your project to run.

**Comment by Raynos** [comment]
I can't reproduce either and it's not an issue for me.

I've since changed my workflows to not enable long stacktraces by default but only enable it for a single file.

**Comment by CrabDude** [comment]
Cool. Always wanting this to be as performant as possible, but there's only
so much blood you can squeeze from a stone. :)

On Monday, August 31, 2015, Jake Verbaten <notifications@github.com> wrote:

> I can't reproduce either and it's not an issue for me.
>
> I've since changed my workflows to not enable long stacktraces by default
> but only enable it for a single file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CrabDude/trycatch/issues/39#issuecomment-136606207>.
>


-- 
Adam Crabtree
Noderiety
PO Box 3823
Los Altos, CA 94024
Telephone: *(*469) 777-8415 <https://mail.google.com/>
Email: dude@noderiety.com

This e-mail message is intended for the use of the addressee(s) only and
may contain information that is privileged-confidential and exempt from
disclosure under applicable law.  If the reader of the message is not the
intended recipient or agent responsible for delivering the message to the
intended recipient, you are hereby notified that any review, dissemination,
distribution or copying of this communication is strictly prohibited.  If
you receive this communication in error, please notify us immediately by
reply e-mail and delete the original message.  Thank you.
