### ISSUE TITLE
Enforce hookit version ^1.1.3 instead of 1.x.x

### ISSUE THREAD

**Issue by mickaeltr** [CrabDude/trycatch#42]
Hello,

When upgrading from trycatch 1.5.11 to 1.5.19, I encountered a setTimeOut bug caused by hookit. I described it here: https://github.com/iriscouch/follow/issues/70

It looks like this bug has been fixed in hookit 1.1.2 or 1.1.3.. Would it be possible, for trycatch 1.5.20, to pull hookit 1.1.3 (instead of any 1.x.x version)?

Thanks

**Comment by CrabDude** [comment]
Sure. Give me a second.

On Sunday, September 13, 2015, Mickaël Tricot <notifications@github.com>
wrote:

> Hello,
>
> When upgrading from trycatch 1.5.11 to 1.5.19, I encountered a setTimeOut
> bug caused by hookit. I described it here: iriscouch/follow#70
> <https://github.com/iriscouch/follow/issues/70>
>
> It looks like this bug has been fixed in hookit 1.1.2 or 1.1.3.. Would it
> be possible, for trycatch 1.5.20, to pull hookit 1.1.3 (instead of any
> 1.x.x version)?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CrabDude/trycatch/issues/42>.
>


-- 
Adam Crabtree
Noderiety
PO Box 3823
Los Altos, CA 94024
Telephone: *(*469) 777-8415 <https://mail.google.com/>
Email: dude@noderiety.com

This e-mail message is intended for the use of the addressee(s) only and
may contain information that is privileged-confidential and exempt from
disclosure under applicable law.  If the reader of the message is not the
intended recipient or agent responsible for delivering the message to the
intended recipient, you are hereby notified that any review, dissemination,
distribution or copying of this communication is strictly prohibited.  If
you receive this communication in error, please notify us immediately by
reply e-mail and delete the original message.  Thank you.

**Comment by CrabDude** [comment]
Published: trycatch@1.5.20

**Comment by mickaeltr** [comment]
Great! Thanks a lot
