### ISSUE TITLE
Add support for node.js version 5.0.0

### ISSUE THREAD

**Issue by kavesh** [CrabDude/trycatch#44]
Hi,
 We have used trycatch module with node.js version 0.10.40  and it works fine, recently we had to update the node.js to version 5.0.0 for testing the application on stable version. When we were accessing any of the api, we started getting an error and my server started to shutdown.
The exception that we are getting is listed below
**error: error: In UserController : ViewDetails() :: Error is  TypeError: Cannot read property 'length' of undefined
/home/user/TestSails/node_modules/trycatch/lib/trycatch.js:222
      throw err
      ^**

**Comment by CrabDude** [comment]
It looks like all tests are passing for all supported versions of node.js for the latest version @1.5.20.

I'm pretty sure the issue you're seeing was fixed in a previous version. Try updating your installed version .

**Comment by kavesh** [comment]
Thanks a lot.
