### ISSUE TITLE
Context issue : Using trycatch within function and calling same function insite it.

### ISSUE THREAD

**Issue by rajeshpanwar** [CrabDude/trycatch#48]
Hi CrabDude,

My Code : 
```
var trycatch = require('trycatch');
var fun = function (one, cb) {
    var obj = {
        name: one
    }
    trycatch(function () {
        setTimeout(function () {
            console.log("======", one);
            if (one == "function2") {
                return cb();
            }
            fun("function2", function () {
                if (one == "function1") {
                    throw new Error("Something Went Wrong");
                }
                cb();
            });
        }, 2000)
    }, function (e) {
        console.log("Error >>>>>", obj, e);
    });
}

fun("function1", function () {
    console.log("Success >>>>>");
})
```
Output : 
====== function1
====== function2
Error >>>>> { name: 'function2' } [Error: Something Went Wrong]

My inside function "fun" has been finished but still getting context of it. I want to get context of function in which error occurred. 

I want to get output : 
====== function1
====== function2
Error >>>>> { name: '**function1**' } [Error: Something Went Wrong]

How can I get above output ?

**Comment by CrabDude** [comment]
This is working as designed, but I suspect the confusion lies in that you're recursively nesting 2 `trycatch` calls. This acts like you would expect a normal `try/catch` to work wrt nesting and catching.

For example:
```js
function foo(id) {
    if (id === 'b') throw new Error
    try {
        foo('b')
    } catch (e) {
        // re-throw to have outer catch handle the error:
        // if (id === 'b') throw e
        console.log('ID: ', id)
    }
}
foo('a')
// Output: 'ID: b'
```

If you want the desired output, you would need to re-throw the error to allow for the outer catch function to handle it. Happy to try to provide further examples / illustrations.
